### ISSUE TITLE
Тест: установка стационара.

### ISSUE THREAD

**Issue by Noitorra** [Noitorra/rarefied-gas-solver#3]
<h2>Постановка задачи</h2>

В задаче устанавливаются граничные условия диффузного отражения на верхней и нижней стенке, с температурами T1 = 1800K на нижней и T2 = 900K на верхней соответственно.
Граничными условиями слева и справа являются условия постоянного давления P = 150Па и температурой sqrt(T1 \* T2). 

<h2>Результаты</h2>

Ниже приведены графики распределения температуры, давления, концентрации и потока.
![conc2000](https://cloud.githubusercontent.com/assets/3650297/7868987/238027d2-0599-11e5-8bb9-8078b5a8136c.png)
![flow2000](https://cloud.githubusercontent.com/assets/3650297/7868992/2b39891e-0599-11e5-82f6-354e681cfd19.png)
![pressure2000](https://cloud.githubusercontent.com/assets/3650297/7868995/30c8ad42-0599-11e5-8b44-8033d155f28b.png)
![temp2000](https://cloud.githubusercontent.com/assets/3650297/7869000/36e9a6ae-0599-11e5-95f7-e0fcdfcf035c.png)

**Comment by prohor33** [comment]
Вопрос почему при разных граничных условиях получаются разные картинки? (Градиент или "кривой" градиент)

**Comment by prohor33** [comment]
Картинки с первого взгяды выглядят как начало возмущений, но на самом деле, похоже, что это просто небольшие числовые ошибки граничных условий (постановка и пересчет обратно)
